# -*- coding: utf-8 -*-
"""springboardintern.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10VPbGKTcw8mJCTTXGKG_rFAoUAbGQ_Ya
"""

!pip install nltk spacy gensim scikit-learn pandas numpy matplotlib wordcloud plotly transformers
!python -m spacy download en_core_web_sm

import nltk, re, spacy, pandas as pd, numpy as np
from nltk.corpus import stopwords
from gensim import corpora, models
from wordcloud import WordCloud
import matplotlib.pyplot as plt
import plotly.express as px
from transformers import pipeline

nltk.download('stopwords')
stop_words = set(stopwords.words('english'))
nlp = spacy.load("en_core_web_sm")

from google.colab import files
!pip install python-docx
!pip install PyMuPDF
import docx
import fitz  # PyMuPDF

uploaded = files.upload()

filename = list(uploaded.keys())[0]
text_data = ""

if filename.endswith('.txt'):
    try:
        with open(filename, 'r', encoding='utf-8') as f:
            text_data = f.read()
    except UnicodeDecodeError:
        with open(filename, 'r', encoding='latin-1') as f:
            text_data = f.read()

elif filename.endswith('.csv'):
    df = pd.read_csv(filename)
    text_data = ' '.join(df.astype(str).values.flatten())

elif filename.endswith('.docx'):
    doc = docx.Document(filename)
    text_data = ' '.join([para.text for para in doc.paragraphs])

elif filename.endswith('.pdf'):
    text_pages = []
    with fitz.open(filename) as pdf:
        for page in pdf:
            text_pages.append(page.get_text("text"))
    text_data = ' '.join(text_pages)

else:
    print("Unsupported file format.")

print("✅ File processed successfully!")
print("\nSample text preview:\n")
print(text_data[:1000])

def preprocess(text):
    text = re.sub(r'[^a-zA-Z]', ' ', text.lower())
    doc = nlp(text)
    tokens = [token.lemma_ for token in doc
              if token.text not in stop_words and len(token.text) > 2]
    return tokens

tokens = preprocess(text_data)
print(tokens[:50])

def lda_model(tokens_list):
    dictionary = corpora.Dictionary([tokens_list])
    corpus = [dictionary.doc2bow(tokens_list)]
    lda = models.LdaModel(corpus, num_topics=5, id2word=dictionary, passes=10)
    return lda.print_topics(num_words=5)

topics = lda_model(tokens)
for t in topics:
    print(t)

sentiment_pipeline = pipeline("sentiment-analysis")

sentences = text_data.split('.')[:10]
results = sentiment_pipeline(sentences)

for s, r in zip(sentences, results):
    print(f"{s.strip()} → {r}")

summarizer = pipeline("summarization", model="facebook/bart-large-cnn")

summary = summarizer(text_data[:3000], max_length=150, min_length=40, do_sample=False)
print("🔹 Summary:\n", summary[0]['summary_text'])

wc = WordCloud(width=800, height=400, background_color='white').generate(' '.join(tokens))
plt.figure(figsize=(10,5))
plt.imshow(wc, interpolation='bilinear')
plt.axis('off')
plt.show()

df_sent = pd.DataFrame(results)
fig = px.bar(df_sent, x=df_sent.index, y='score', color='label',
             title='Sentiment Scores per Sentence')
fig.show()

print("---- Key Insights ----")
print(f"Total Words: {len(tokens)}")
pos = sum(1 for r in results if r['label'] == 'POSITIVE')
neg = sum(1 for r in results if r['label'] == 'NEGATIVE')
neu = len(results) - (pos + neg)
print(f"Positive: {pos}, Negative: {neg}, Neutral: {neu}")
print("\nMain Topics:")
for t in topics:
    print(t)